# Generated by Django 5.0.1 on 2024-01-31 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='customer_name')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='id_number')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='contact_phone')),
                ('contact_email', models.EmailField(max_length=254, unique=True, verbose_name='contact_email')),
                ('date_of_birth', models.DateField(verbose_name='date_of_birth')),
                ('nationality', models.CharField(choices=[('kenyan', 'kenyan'), ('ugandan', 'ugandan'), ('tanzanian', 'tanzanian'), ('rwandees', 'rwandees')], max_length=50, null=True, verbose_name='nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100, verbose_name='business_name')),
                ('business_registration_date', models.DateField(verbose_name='business_registration')),
                ('county', models.PositiveSmallIntegerField(choices=[(1, 'NAIROBI'), (2, 'MOMBASA')], null=True)),
                ('building_name', models.CharField(max_length=100, null=True)),
                ('sub_county', models.PositiveSmallIntegerField(choices=[(1, 'NAIROBI'), (2, 'MOMBASA')], null=True)),
                ('ward', models.PositiveSmallIntegerField(choices=[(1, 'NAIROBI'), (2, 'MOMBASA')], null=True)),
                ('floor', models.PositiveSmallIntegerField(null=True)),
                ('business_category', models.ForeignKey(choices=[(1, 'SMALL SCALE'), (2, 'LARGE SCALE')], on_delete=django.db.models.deletion.CASCADE, to='customer.businesscategories')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
