# Generated by Django 5.0.1 on 2024-02-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_category',
            field=models.PositiveSmallIntegerField(verbose_name='business_category'),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='subcounty_name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
