# Generated by Django 5.0.1 on 2024-01-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SMALL SCALE'), (2, 'LARGE SCALE')], verbose_name='business_category'),
        ),
    ]
