# Generated by Django 5.0.1 on 2024-01-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='building_name',
            field=models.CharField(choices=[('Nairobi', [('View Park Towers', 'view park Towers'), ('Kenyatta International Conference Centre (KICC)', 'Kenyatta International Conference Centre (KICC)'), ('Nation Centre', 'Nation Centre')]), ('Mombasa', [('City Mall', 'City Mall'), ('Mombasa Beach Hotel', 'Mombasa Beach Hotel'), ('Nyali Centre', 'Nyali Centre')])], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='floor',
            field=models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('1st Floor', '1st Floor'), ('2nd Floor', '2nd Floor'), ('3rd Floor', '3rd Floor'), ('4th Floor', '4th Floor')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='sub_county',
            field=models.CharField(choices=[], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='ward',
            field=models.CharField(choices=[], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='county',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NAIROBI'), (2, 'MOMBASA')], null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(choices=[('kenyan', 'kenyan'), ('ugandan', 'ugandan'), ('tanzanian', 'tanzanian'), ('rwandees', 'rwandees')], max_length=50, null=True, verbose_name='nationality'),
        ),
    ]
