# Generated by Django 5.0.1 on 2024-02-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_business_business_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='county',
            field=models.CharField(max_length=100, null=True, verbose_name='county'),
        ),
        migrations.AlterField(
            model_name='business',
            name='sub_county',
            field=models.CharField(max_length=100, null=True, verbose_name='sub_county'),
        ),
        migrations.AlterField(
            model_name='business',
            name='ward',
            field=models.CharField(max_length=50, null=True, verbose_name='ward'),
        ),
    ]
