# Generated by Django 3.2.12 on 2024-02-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_business_business_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(choices=[('rwandees', 'rwandees'), ('ugandan', 'ugandan'), ('tanzanian', 'tanzanian'), ('kenyan', 'kenyan')], max_length=50, null=True, verbose_name='nationality'),
        ),
    ]
