# Generated by Django 5.0.1 on 2024-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_business_sub_county_alter_business_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='contact_email'),
        ),
    ]
