# Generated by Django 3.2.12 on 2024-02-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(choices=[('kenyan', 'Kenyan'), ('ugandan', 'Ugandan'), ('tanzanian', 'Tanzanian'), ('rwandese', 'Rwandese')], max_length=50, null=True, verbose_name='nationality'),
        ),
    ]
